/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import static java.lang.Character.isDigit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jakub
 */
public class NauczycielJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NauczycielJFrame
     */
    public NauczycielJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPrzydzial = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nauczycielTable = new javax.swing.JTable();
        jPanelZarzadzajKontem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        starehasloField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        potwierdzPasswordField = new javax.swing.JPasswordField();
        jButtonZmienHaslo = new javax.swing.JButton();
        jPanelMenu = new javax.swing.JPanel();
        jButtonZarzadzajKontem = new javax.swing.JButton();
        jButtonPrzydzial = new javax.swing.JButton();
        wylogujButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel Nauczyciela");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.add(jPanel5);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelPrzydzial.setBackground(new java.awt.Color(255, 255, 255));

        nauczycielTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Przedmiot", "wykład", "ćwiczenia", "labolatoria", "projekt"
            }
        ));
        jScrollPane1.setViewportView(nauczycielTable);

        javax.swing.GroupLayout jPanelPrzydzialLayout = new javax.swing.GroupLayout(jPanelPrzydzial);
        jPanelPrzydzial.setLayout(jPanelPrzydzialLayout);
        jPanelPrzydzialLayout.setHorizontalGroup(
            jPanelPrzydzialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrzydzialLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelPrzydzialLayout.setVerticalGroup(
            jPanelPrzydzialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrzydzialLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanelPrzydzial);

        jPanelZarzadzajKontem.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        jLabel1.setText("Zmień hasło");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Stare hasło:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Nowe hasło:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Potwierdź hasło:");

        jButtonZmienHaslo.setBackground(new java.awt.Color(0, 51, 51));
        jButtonZmienHaslo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButtonZmienHaslo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonZmienHaslo.setText("Zmień");
        jButtonZmienHaslo.setBorder(null);
        jButtonZmienHaslo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZmienHasloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelZarzadzajKontemLayout = new javax.swing.GroupLayout(jPanelZarzadzajKontem);
        jPanelZarzadzajKontem.setLayout(jPanelZarzadzajKontemLayout);
        jPanelZarzadzajKontemLayout.setHorizontalGroup(
            jPanelZarzadzajKontemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelZarzadzajKontemLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(jPanelZarzadzajKontemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelZarzadzajKontemLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelZarzadzajKontemLayout.createSequentialGroup()
                        .addGroup(jPanelZarzadzajKontemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelZarzadzajKontemLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanelZarzadzajKontemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanelZarzadzajKontemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(starehasloField)
                            .addComponent(newPasswordField)
                            .addComponent(potwierdzPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonZmienHaslo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );
        jPanelZarzadzajKontemLayout.setVerticalGroup(
            jPanelZarzadzajKontemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZarzadzajKontemLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanelZarzadzajKontemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(starehasloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelZarzadzajKontemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelZarzadzajKontemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(potwierdzPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButtonZmienHaslo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanelZarzadzajKontem);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelMenu.setBackground(new java.awt.Color(0, 51, 51));

        jButtonZarzadzajKontem.setBackground(new java.awt.Color(0, 51, 51));
        jButtonZarzadzajKontem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButtonZarzadzajKontem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonZarzadzajKontem.setText("Zarządzaj kontem");
        jButtonZarzadzajKontem.setBorder(null);
        jButtonZarzadzajKontem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZarzadzajKontemActionPerformed(evt);
            }
        });

        jButtonPrzydzial.setBackground(new java.awt.Color(0, 51, 51));
        jButtonPrzydzial.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButtonPrzydzial.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrzydzial.setText("Przydział");
        jButtonPrzydzial.setBorder(null);
        jButtonPrzydzial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrzydzialActionPerformed(evt);
            }
        });

        wylogujButton.setBackground(new java.awt.Color(0, 51, 51));
        wylogujButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        wylogujButton.setForeground(new java.awt.Color(255, 255, 255));
        wylogujButton.setText("Wyloguj");
        wylogujButton.setBorder(null);
        wylogujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wylogujButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPrzydzial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonZarzadzajKontem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wylogujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButtonPrzydzial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButtonZarzadzajKontem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(wylogujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1330, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(814, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(192, 192, 192)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(386, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 453, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZmienHasloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZmienHasloActionPerformed
        String has=starehasloField.getText();
        String noweHas=newPasswordField.getText();
        String potwierdzHas=potwierdzPasswordField.getText();
        zmienHaslo(has, noweHas, potwierdzHas);
    }//GEN-LAST:event_jButtonZmienHasloActionPerformed

    private void jButtonZarzadzajKontemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZarzadzajKontemActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonZarzadzajKontemActionPerformed

    private void jButtonPrzydzialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrzydzialActionPerformed
        wyczyscNauczycielTable();
        jTabbedPane1.setSelectedIndex(0);
        wyswietlPrzydzial();
    }//GEN-LAST:event_jButtonPrzydzialActionPerformed

    private void wylogujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wylogujButtonActionPerformed
        new ZalogujJFrame().setVisible(true);
                                this.dispose();
    }//GEN-LAST:event_wylogujButtonActionPerformed

    public static void AddRowToNauczycielJtable(Object[] dataRow){
        DefaultTableModel model = (DefaultTableModel)nauczycielTable.getModel();
        model.addRow(dataRow);
    }
    
    public static void wyczyscNauczycielTable(){
        DefaultTableModel dm = (DefaultTableModel)nauczycielTable.getModel();
        int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }
    
    public void wyswietlPrzydzial(){
        int idOsoba=0;
        String selectQuery = "SELECT ID_OSOBA FROM KONTO WHERE LOGIN=?";
        String query = "SELECT PR.NAZWA, P.ILOSC_GRUP_WYKL, P.ILOSC_GRUP_CW, P.ILOSC_GRUP_LAB, P.ILOSC_GRUP_PROJ"
                + " FROM PRZYDZIAL P  LEFT JOIN PRZEDMIOT PR ON PR.ID_PRZEDMIOT = P.ID_PRZEDMIOT WHERE P.ID_OSOBA=?";
        DBCONNECT dbConnect= new DBCONNECT();
        String className=dbConnect.getClassName();
        String baza=dbConnect.getBaza();
        String loginBaza=dbConnect.getLoginBaza();
        String hasloBaza=dbConnect.getHasloBaza();
        Connection conn = null;
        ZalogujJFrame logframe= new ZalogujJFrame();
        String login=logframe.getLogin();
                try {
                    PreparedStatement psmt;
                    Class.forName(className);
                    conn = DriverManager.getConnection(baza,loginBaza,hasloBaza);
                    psmt = conn.prepareStatement(selectQuery);
                    psmt.setString(1,login);
                    ResultSet rs = psmt.executeQuery();
                    if(rs.next()){
                        idOsoba=Integer.parseInt(rs.getString(1));
                    }
                    psmt = conn.prepareStatement(query);
                    psmt.setInt(1,idOsoba);
                    rs = psmt.executeQuery();
                    while(rs.next()){
                            NauczycielJFrame.AddRowToNauczycielJtable(new Object[]{
                                                                        rs.getString(1),
                                                                        rs.getString(2),
                                                                        rs.getString(3),
                                                                        rs.getString(4),
                                                                        rs.getString(5)
                });
                            
                            
          }
                        conn.close();
                        System.out.println("zamknięto połączenie z bazą!");
                }
                //Wyrzuć wyjątki jężeli nastąpią błędy z podłączeniem do bazy danych lub blędy zapytania o dane
                catch(ClassNotFoundException wyjatek) {
                        System.out.println("Problem ze sterownikiem");
                        System.out.println(wyjatek.getMessage());
                }
 
                catch(SQLException wyjatek) {
                        //e.printStackTrace();
                        //System.out.println("Problem z logowaniem\nProsze sprawdzic:\n nazwę użytkownika, hasło, nazwę bazy danych lub adres IP serwera");
                        System.out.println("SQLException: " + wyjatek.getMessage());
                    System.out.println("SQLState: " + wyjatek.getSQLState());
                    System.out.println("VendorError: " + wyjatek.getErrorCode());
                }
    }
    
    public void zmienHaslo(String has,String noweHas,String potwierdzHas){
        String query = "Select * FROM KONTO WHERE LOGIN=? AND HASLO=?";
        String updateQuery = "UPDATE KONTO SET HASLO = ? WHERE LOGIN=? AND HASLO=?";
        DBCONNECT dbConnect= new DBCONNECT();
        String className=dbConnect.getClassName();
        String baza=dbConnect.getBaza();
        String loginBaza=dbConnect.getLoginBaza();
        String hasloBaza=dbConnect.getHasloBaza();
        Connection conn = null;
        ZalogujJFrame logframe= new ZalogujJFrame();
        String login=logframe.getLogin();
        System.out.println("login:"+login);
        
        try {
            Statement stmt;
            PreparedStatement psmt;
            Class.forName(className);
            System.out.println("driver zaladowany");
            //Ustawiamy dane dotyczące podłączenia
            conn = DriverManager.getConnection(baza,loginBaza,hasloBaza);
            System.out.println("baza?");
            stmt = conn.createStatement();
            psmt = conn.prepareStatement(query);
            psmt.setString(1,login);
            psmt.setString(2,has);
            ResultSet rs = psmt.executeQuery();

            if(rs.next()){
                if(sprawdzHaslo(noweHas)){
        
                if(noweHas.equals(potwierdzHas)){
                    psmt = conn.prepareStatement(updateQuery);
                    psmt.setString(1,noweHas);
                    psmt.setString(2,login);
                    psmt.setString(3,has);
                    psmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Hasło zostało zmienione!");
                }else{
                    JOptionPane.showMessageDialog(null, "Hasła się różnią!");
                }
                }else{
           JOptionPane.showMessageDialog(null, "Nowe hasło jest za słabe!"); 
        }
            }
            else{
                JOptionPane.showMessageDialog(null, "Złe hasło!");
            }
            conn.close();
        }
        //Wyrzuć wyjątki jężeli nastąpią błędy z podłączeniem do bazy danych lub blędy zapytania o dane
        catch(ClassNotFoundException wyjatek) {
            System.out.println("Problem ze sterownikiem");
            System.out.println(wyjatek.getMessage());
        }

        catch(SQLException wyjatek) {
            //e.printStackTrace();
            //System.out.println("Problem z logowaniem\nProsze sprawdzic:\n nazwę użytkownika, hasło, nazwę bazy danych lub adres IP serwera");
            System.out.println("SQLException: " + wyjatek.getMessage());
            System.out.println("SQLState: " + wyjatek.getSQLState());
            System.out.println("VendorError: " + wyjatek.getErrorCode());
        }
    }
    
    public boolean sprawdzHaslo(String haslo){
        int dlugosc=haslo.length();
        boolean znakSpecjalny=false;
        boolean cyfra=false;
        System.out.println(dlugosc);
        for(int i=0;i<dlugosc;i++){
            
        
        char znak=haslo.charAt(i);
        if(isDigit(znak)){
           cyfra=true; 
           System.out.println(cyfra);
        }
        if(((znak>=0x21)&&(znak<=0x2f))||((znak>=0x3a)&&(znak<=0x40))||((znak>=0x5b)&&(znak<=0x60))||((znak>=0x7b)&&(znak<=0x7e))){
            znakSpecjalny=true;
            System.out.println(znakSpecjalny);
        }
        }
        if(cyfra&&znakSpecjalny&&(dlugosc>6)){
            return true;
        }else{
            return false;
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NauczycielJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NauczycielJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NauczycielJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NauczycielJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NauczycielJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrzydzial;
    private javax.swing.JButton jButtonZarzadzajKontem;
    private javax.swing.JButton jButtonZmienHaslo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelPrzydzial;
    private javax.swing.JPanel jPanelZarzadzajKontem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JTable nauczycielTable;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JPasswordField potwierdzPasswordField;
    private javax.swing.JPasswordField starehasloField;
    private javax.swing.JButton wylogujButton;
    // End of variables declaration//GEN-END:variables
}
